# =====================================================================
# CONFIGURATION PRESIDIO POUR DOCUMENTS FRANÇAIS/BELGES
# =====================================================================

# Configuration du moteur de langage (NLP)
nlp_engine_name: spacy
supported_languages: [en, fr]
models:
  - lang_code: en
    model_name: en_core_web_lg
  - lang_code: fr
    model_name: fr_core_news_sm

# Configuration du comportement du moteur NLP
ner_model_configuration:
  labels_to_ignore:
    - MISC
    - ORG  # Éviter les faux positifs sur les noms d'organisations
  

# Configuration des détecteurs (Recognizers)
recognizer_registry:
  # Charger d'abord les détecteurs par défaut
  - default


