version: '3.8'

services:
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    restart: unless-stopped

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    restart: unless-stopped
