# Fichier : docker-compose.yml
version: '3.8'

services:
  # Le service principal de l'API
  presidio-api:
    image: mcr.microsoft.com/presidio-api:latest # <-- CORRIGÉ
    container_name: presidio-api
    restart: unless-stopped
    ports:
      - "3000"
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer
    environment:
      PRESIDIO_ANALYZER_SERVICE_URL: http://presidio-analyzer:5001
      PRESIDIO_ANONYMIZER_SERVICE_URL: http://presidio-anonymizer:5002

  # Le service qui détecte les PII
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    container_name: presidio-analyzer
    restart: unless-stopped
    ports:
      - "5001"

  # Le service qui anonymise
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest # <-- CORRIGÉ
    container_name: presidio-anonymizer
    restart: unless-stopped
    ports:
      - "5002"
