# Fichier : docker-compose.yml
version: '3.8'

services:
  # Le service principal de l'API que votre app Next.js appellera
  presidio-api:
    image: mcr.microsoft.com/presidio-api:latest
    container_name: presidio-api
    restart: unless-stopped
    ports:
      - "3000"
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer
    environment:
      PRESIDIO_ANALYZER_SERVICE_URL: http://presidio-analyzer:5001
      PRESIDIO_ANONYMIZER_SERVICE_URL: http://presidio-anonymizer:5002

  # Le service qui détecte les PII (avec le support du français)
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    container_name: presidio-analyzer
    restart: unless-stopped
    ports:
      - "5001"
    volumes:
      # === LE CHEMIN CORRECT TROUVÉ GRÂCE À VOUS EST ICI ===
      # On monte notre configuration locale dans le VRAI répertoire du conteneur.
      - ./conf:/usr/bin/presidio-analyzer/presidio_analyzer/conf

  # Le service qui anonymise les PII détectées
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    ports:
      - "5002"
