# Fichier : docker-compose.yml
version: '3.8'

services:
  # Le service principal de l'API que votre app Next.js appellera
  presidio-api:
    image: mcr.microsoft.com/presidio-api:latest
    container_name: presidio-api
    restart: unless-stopped
    ports:
      - "3000" # Coolify gérera l'exposition de ce port
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer
    environment:
      # Ces variables restent nécessaires pour que l'API sache où trouver ses collègues
      PRESIDIO_ANALYZER_SERVICE_URL: http://presidio-analyzer:5001
      PRESIDIO_ANONYMIZER_SERVICE_URL: http://presidio-anonymizer:5002

  # Le service qui détecte les PII (avec le support du français)
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    container_name: presidio-analyzer
    restart: unless-stopped
    ports:
      - "5001"
    volumes:
      # === LA MODIFICATION EST ICI ===
      # On monte notre dossier 'conf' local dans le conteneur.
      # Le contenu de notre fichier ./conf/default.yaml va écraser celui par défaut dans l'image.
      # Note: Le chemin exact peut dépendre de la version de Python dans l'image.
      # python3.9 est le plus probable, mais si ça ne marche pas, on pourra essayer python3.8, python3.10, etc.
      - ./conf:/usr/local/lib/python3.9/site-packages/presidio_analyzer/conf

  # Le service qui anonymise les PII détectées
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    ports:
      - "5002"
