version: '3.8'

services:
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    container_name: presidio-analyzer
    restart: unless-stopped
    ports:
      - "5001"  # Port corrigé selon la doc Microsoft
    environment:
      - PRESIDIO_ANALYZER_DEFAULT_LANGUAGE=fr

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    ports:
      - "5002"  # Port corrigé selon la doc Microsoft
    environment:
      - PRESIDIO_ANONYMIZER_DEFAULT_LANGUAGE=fr
