# =====================================================================
# CONFIGURATION PRESIDIO - v14 (FINALE ET COMPLÈTE)
# =====================================================================
supported_languages: [en, fr]

# 1. CONFIGURATION DU MOTEUR NLP
# =====================================================================
nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: en
      model_name: en_core_web_lg
    - lang_code: fr
      model_name: fr_core_news_lg 
      ner_model_configuration:
        labels_to_ignore:
          - MISC
          - CARDINAL
          - EVENT
          - LANGUAGE
          - LAW
          - ORDINAL
          - PERCENT
          - PRODUCT
          - QUANTITY
          - WORK_OF_ART
        confidence_thresholds:
          DEFAULT_CONFIDENCE: 0.65
          PERSON: 0.85
          LOCATION: 0.4
          ORGANIZATION: 0.55

# 2. CONFIGURATION DU REGISTRE DES DÉTECTEURS
# =====================================================================
recognizer_registry:
  load_predefined_recognizers: true
  
  recognizers:
    # --- DÉTECTEURS FIABLES ET PRÉCIS UNIQUEMENT ---

    - name: CustomDateRecognizer
      supported_language: fr
      supported_entity: CUSTOM_DATE
      patterns:
        - name: Date JJ MM AAAA
          regex: "\\b(0[1-9]|[12][0-9]|3[01])\\s*(?:janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)\\s*(19|20)\\d{2}\\b"
          score: 1.0
        - name: Date JJ/MM/AAAA
          regex: "\\b(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\\d{2}\\b"
          score: 1.0
      context: ["date", "conclu le", "fait le", "né le"]

    - name: PhoneRecognizer
      supported_language: fr
      supported_entity: PHONE_NUMBER
      patterns:
        - name: Phone Pattern Flexible
          regex: "\\b(?:\\+|00)(?:32|33)\\s?[1-9](?:[\\s.-]?\\d{1,3}){2,4}\\b"
          score: 0.9
      context: ["téléphone", "tel", "mobile", "gsm", "contact"]
    
    - name: CreditCardRecognizer
      supported_language: fr
      supported_entity: CREDIT_CARD_NUMBER
      patterns:
        - name: Credit Card with spaces
          regex: "\\b(?:4[0-9]{3}(?:[ -]?[0-9]{4}){3}|5[1-5][0-9]{2}(?:[ -]?[0-9]{4}){3})\\b"
          score: 0.95
      context: ["carte bancaire", "visa", "mastercard"]

    - name: IbanRecognizer
      supported_language: fr
      supported_entity: IBAN
      patterns: [{name: IBAN Pattern, regex: "\\b[A-Z]{2}[0-9]{2}\\s?(?:[A-Z0-9]{4}\\s?){2,7}[A-Z0-9]{1,4}\\b", score: 0.95}]
      context: ["iban", "compte", "bancaire"]
      
    - name: SWIFTRecognizer
      supported_language: fr
      supported_entity: SWIFT_CODE
      patterns:
        - name: BIC/SWIFT Code
          regex: "\\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\\b"
          score: 1.0
      context: ["bic", "swift"]

    - name: MoneyRecognizer
      supported_language: fr
      supported_entity: MONEY
      patterns:
        - name: Money Pattern EUR
          regex: "(?:EUR|€)\\s*\\d{1,3}(?:[.,\\s]\\d{3})*(?:[.,]\\d{2})?|\\d{1,3}(?:[.,\\s]\\d{3})*(?:[.,]\\d{2})?\\s*(?:EUR|€)"
          score: 0.9
      context: ["montant", "prix", "eur", "euros"]
    
    # --- NUMÉROS D'IDENTIFICATION ---
    - name: FrenchINSEERecognizer
      supported_language: fr
      supported_entity: FR_SOCIAL_SECURITY_NUMBER
      patterns:
        - name: INSEE Pattern with flexible spaces
          regex: "\\b[12]\\s*[0-9]{2}\\s*(?:0[1-9]|1[0-2])\\s*(?:2[ABab]|[0-9]{2})\\s*[0-9]{3}\\s*[0-9]{3}\\s*[0-9]{2}\\b"
          score: 0.95
      context: ["sécurité sociale", "insee", "nir"]
      
    - name: BelgianNRNRecognizer
      supported_language: fr
      supported_entity: BE_NATIONAL_REGISTER_NUMBER
      patterns: [{name: NRN Pattern, regex: "\\b[0-9]{2}\\.[0-9]{2}\\.[0-9]{2}-[0-9]{3}\\.[0-9]{2}\\b", score: 1.0}]
      context: ["registre national", "nrn", "niss"]

    - name: BelgianEnterpriseRecognizer
      supported_language: fr
      supported_entity: BE_ENTERPRISE_NUMBER
      patterns: [{name: BE Enterprise Number, regex: "\\bBE\\s?0\\d{3}[\\.\\s]?\\d{3}[\\.\\s]?\\d{3}\\b", score: 0.95}]
      context: ["numéro d'entreprise", "btw", "tva", "BCE", "KBO"]


# 3. LISTE D'EXCLUSION (ALLOW LIST)
# =====================================================================
allow_list:
  - Adresse
  - ADRESSE
  - CONTRAT
  - PROJET
  - CONSEILS
  - PARTIES
  - DOCUMENT
  - DEMANDER
  - CONSEILLERS
  - QUALIFIÉS
  - ÉVALUER
  - IMPLICATIONS
  - UTILISATION
  - ATTENDU
  - QUE
  - OBLIGATION
  - CONVERSION
  - FINANCEMENT
  - QUALIFIÉ
  - PRIX
  - SORTIE
  - TAXES
  - DROITS
  - INFORMATION
  - DISPOSITIONS
  - DIVERSES
  - NOTIFICATIONS
  - Contrat
  - Document
  - Société
  - Investisseur
  - Montant
  - Prêt
  - Intérêt
  - Partie
  - Parties
  - Annexe
  - Remboursement
  - Financement
  - "Juste Valeur Marchande"
  - Échéance
  - Clause
  - Clauses
  - Principe
  - Coûts
  - Article
  - Paragraphe
  - Directeur
  - Gérant
  - Président
  - DocuSign
  - SPRL
  - SA
  - Loi
  - Code
  - Règlement
  - Décret
  - Arrêté
  - Euro
  - EUR
  - Euros
  - Taux
  - Valeur

# 4. CONFIGURATION DES TRANSFORMATIONS D'ANONYMISATION
# =====================================================================
anonymizer_config:
  default_anonymizers:
    # Entités détectées par l'IA (Spacy)
    PERSON: replace
    LOCATION: replace
    ORGANIZATION: replace
    DATE_TIME: replace # Détecteur par défaut de Presidio
    
    # Entités détectées par nos règles personnalisées
    CUSTOM_DATE: replace
    CREDIT_CARD_NUMBER: replace
    EMAIL_ADDRESS: replace # Détecteur par défaut, mais notre règle peut prendre le dessus
    PHONE_NUMBER: replace
    IBAN: replace
    MONEY: replace
    BE_NATIONAL_REGISTER_NUMBER: replace
    BE_ENTERPRISE_NUMBER: replace
    FR_SOCIAL_SECURITY_NUMBER: replace
    SWIFT_CODE: replace
  
  replacements:
    PERSON: "<PERSONNE>"
    LOCATION: "<LIEU>"
    ORGANIZATION: "<ORGANISATION>"
    DATE_TIME: "<DATE>"
    CUSTOM_DATE: "<DATE>"
    CREDIT_CARD_NUMBER: "<NUMERO_CARTE_BANCAIRE>"
    EMAIL_ADDRESS: "<EMAIL>"
    PHONE_NUMBER: "<TELEPHONE>"
    IBAN: "<IBAN>"
    MONEY: "<MONTANT>"
    BE_NATIONAL_REGISTER_NUMBER: "<NRN_BELGE>"
    BE_ENTERPRISE_NUMBER: "<NUM_ENTREPRISE_BE>"
    FR_SOCIAL_SECURITY_NUMBER: "<NUM_SECU_FR>"
    SWIFT_CODE: "<CODE_SWIFT>"
