# =====================================================================
# CONFIGURATION PRESIDIO - v31 (FINALE, ÉPURÉE ET FIABLE)
# =====================================================================
supported_languages: [en, fr]

# 1. CONFIGURATION DU MOTEUR NLP
# =====================================================================
nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: en
      model_name: en_core_web_lg
    - lang_code: fr
      model_name: fr_core_news_lg 
      ner_model_configuration:
        labels_to_ignore:
          - MISC
          - CARDINAL
          - EVENT
          - LANGUAGE
          - LAW
          - ORDINAL
          - PERCENT
          - PRODUCT
          - QUANTITY
          - WORK_OF_ART
        confidence_thresholds:
          DEFAULT_CONFIDENCE: 0.65
          PERSON: 0.85
          LOCATION: 0.4
          ORGANIZATION: 0.55

# 2. CONFIGURATION DU REGISTRE DES DÉTECTEURS
# =====================================================================
recognizer_registry:
  load_predefined_recognizers: true
  
  recognizers:
    # --- DÉTECTEURS FIABLES ET PRÉCIS UNIQUEMENT ---
    - name: CustomDateRecognizer
      supported_language: fr
      supported_entity: CUSTOM_DATE
      patterns:
        - name: Date JJ/MM/AAAA
          regex: "\\b(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\\d{2}\\b"
          score: 1.0
      context: ["date de naissance", "né le", "date"]

    - name: BelgianPhoneRecognizer
      supported_language: fr
      supported_entity: PHONE_NUMBER
      patterns:
        - name: Belgian Mobile Pattern
          regex: "\\b(?:\\+|00)32[\\s.-]?4[6-9][0-9](?:[\\s.-]?\\d{2}){3}\\b"
          score: 1.0
      context: ["téléphone", "tel", "gsm", "mobile"]
      
    - name: IbanRecognizer
      supported_language: fr
      supported_entity: IBAN
      patterns: [{name: IBAN Pattern, regex: "\\b[A-Z]{2}[0-9]{2}\\s?(?:[A-Z0-9]{4}\\s?){2,7}[A-Z0-9]{1,4}\\b", score: 0.95}]
      context: ["iban", "compte"]

    - name: BelgianEnterpriseRecognizer
      supported_language: fr
      supported_entity: BE_ENTERPRISE_NUMBER
      patterns: [{name: BE Enterprise Number, regex: "\\bBE\\s?0\\d{3}[\\.\\s]?\\d{3}[\\.\\s]?\\d{3}\\b", score: 0.95}]
      context: ["numéro d'entreprise", "BCE"]
      
    - name: BelgianNRNRecognizer
      supported_language: fr
      supported_entity: BE_NATIONAL_REGISTER_NUMBER
      patterns: [{name: NRN Pattern, regex: "\\b[0-9]{2}\\.[0-9]{2}\\.[0-9]{2}-[0-9]{3}\\.[0-9]{2}\\b", score: 1.0}]
      context: ["registre national"]
      
# 3. LISTE D'EXCLUSION (ALLOW LIST)
# =====================================================================
allow_list:
  # Liste de sécurité pour les mots en majuscules des contrats
  - CONTRAT
  - PRÊT
  - CONVERTIBLE
  - PROJET
  - CONSTITUE
  - CONTIENT
  - CONSEILS
  - PARTIES
  - UTILISANT
  - DOCUMENT
  - DEVRAIENT
  - TOUJOURS
  - ENVISAGER
  - SOIGNEUSEMENT
  - DEMANDER
  - CONSEILLERS
  - QUALIFIÉS
  - ÉVALUER
  - IMPLICATIONS
  - UTILISATION
  - ATTENDU
  - QUE
  # Liste standard
  - Adresse
  - ADRESSE
  - Société
  - Investisseur
  - Montant
  - Intérêt
  - Partie
  - Annexe
  - Remboursement
  - Conversion
  - Financement
  - Sortie
  - "Juste Valeur Marchande"
  - Échéance
  - Clause
  - Clauses
  - Principe
  - Coûts
  - Notifications
  - Article
  - Paragraphe
  - Directeur
  - Gérant
  - Président
  - DocuSign
  - SPRL
  - SA
  - Loi
  - Code
  - Règlement
  - Décret
  - Arrêté
  - Euro
  - EUR
  - Euros
  - Taux
  - Valeur
  - Prix

# 4. CONFIGURATION DES TRANSFORMATIONS D'ANONYMISATION
# =====================================================================
anonymizer_config:
  default_anonymizers:
    # Entités détectées par l'IA (Spacy) et les règles de base de Presidio
    PERSON: replace
    LOCATION: replace
    ORGANIZATION: replace
    DATE_TIME: replace 
    MONEY: replace
    CREDIT_CARD_NUMBER: replace
    EMAIL_ADDRESS: replace

    # Entités détectées par nos règles personnalisées
    CUSTOM_DATE: replace
    PHONE_NUMBER: replace 
    IBAN: replace
    BE_ENTERPRISE_NUMBER: replace
    BE_NATIONAL_REGISTER_NUMBER: replace
  
  replacements:
    PERSON: "<PERSONNE>"
    LOCATION: "<LIEU>"
    ORGANIZATION: "<ORGANISATION>"
    DATE_TIME: "<DATE>"
    CUSTOM_DATE: "<DATE>"
    CREDIT_CARD_NUMBER: "<NUMERO_CARTE_BANCAIRE>"
    MONEY: "<MONTANT>"
    EMAIL_ADDRESS: "<EMAIL>"
    PHONE_NUMBER: "<TELEPHONE>"
    IBAN: "<IBAN>"
    BE_ENTERPRISE_NUMBER: "<NUM_ENTREPRISE_BE>"
    BE_NATIONAL_REGISTER_NUMBER: "<NRN_BELGE>"
