# Configuration minimale pour test
nlp_engine_name: spacy
supported_languages: [en, fr]
models:
  - lang_code: en
    model_name: en_core_web_lg
  - lang_code: fr
    model_name: fr_core_news_sm

# Commentez temporairement les reconnaisseurs personnalisés
# recognizer_registry:
#   - default
#   - presidio_config.custom_recognizers.custom_recognizers
