# =====================================================================
# CONFIGURATION PRESIDIO - v8 (NETTOYÉE ET FIABLE)
# =====================================================================
supported_languages: [en, fr]

# 1. CONFIGURATION DU MOTEUR NLP
# =====================================================================
nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: en
      model_name: en_core_web_lg
    - lang_code: fr
      model_name: fr_core_news_lg 
      ner_model_configuration:
        labels_to_ignore:
          - MISC
          - CARDINAL
          - EVENT
          - LANGUAGE
          - LAW
          - ORDINAL
          - PERCENT
          - PRODUCT
          - QUANTITY
          - WORK_OF_ART
        confidence_thresholds:
          DEFAULT_CONFIDENCE: 0.65
          PERSON: 0.85
          LOCATION: 0.4
          DATE_TIME: 0.4
          ORGANIZATION: 0.7

# 2. CONFIGURATION DU REGISTRE DES DÉTECTEURS
# =====================================================================
recognizer_registry:
  load_predefined_recognizers: true
  
  recognizers:
    # --- DÉTECTEURS FIABLES ET PRÉCIS UNIQUEMENT ---

    - name: CustomDateRecognizer
      supported_language: fr
      supported_entity: CUSTOM_DATE
      patterns:
        - name: Date DD/MM/YYYY
          regex: "\\b(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\\d{2}\\b"
          score: 1.0
      context: ["date"]

    - name: EmailRecognizer
      supported_language: fr
      supported_entity: EMAIL_ADDRESS
      patterns: [{name: Email Pattern, regex: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b", score: 1.0}]
      context: ["email", "courriel", "mail"]

    - name: PhoneRecognizer
      supported_language: fr
      supported_entity: PHONE_NUMBER
      patterns: [{name: Phone Pattern (FR/BE/LUX), regex: "\\b(?:(?:\\+|00)?(?:32|33|352)|0)\\s?[1-9](?:[\\s.-]?\\d{2}){3,4}\\b", score: 0.8}]
      context: ["téléphone", "tel", "mobile", "gsm", "contact"]

    - name: CreditCardRecognizer
      supported_language: fr
      supported_entity: CREDIT_CARD_NUMBER
      patterns:
        - name: Credit Card with spaces
          regex: "\\b(?:4[0-9]{3}(?:[ -]?[0-9]{4}){3}|5[1-5][0-9]{2}(?:[ -]?[0-9]{4}){3})\\b"
          score: 0.95
      context: ["carte bancaire", "visa", "mastercard"]

    - name: IbanRecognizer
      supported_language: fr
      supported_entity: IBAN
      patterns: [{name: IBAN Pattern, regex: "\\b[A-Z]{2}[0-9]{2}\\s?(?:[A-Z0-9]{4}\\s?){2,7}[A-Z0-9]{1,4}\\b", score: 0.95}]
      context: ["iban", "compte", "bancaire"]

    - name: FrenchINSEERecognizer
      supported_language: fr
      supported_entity: FR_SOCIAL_SECURITY_NUMBER
      patterns:
        - name: INSEE Pattern with flexible spaces
          regex: "\\b[12]\\s*[0-9]{2}\\s*(?:0[1-9]|1[0-2])\\s*(?:2[ABab]|[0-9]{2})\\s*[0-9]{3}\\s*[0-9]{3}\\s*[0-9]{2}\\b"
          score: 0.95
      context: ["sécurité sociale", "insee", "nir"]
      
    - name: BelgianNRNRecognizer
      supported_language: fr
      supported_entity: BE_NATIONAL_REGISTER_NUMBER
      patterns: [{name: NRN Pattern, regex: "\\b[0-9]{2}\\.[0-9]{2}\\.[0-9]{2}-[0-9]{3}\\.[0-9]{2}\\b", score: 1.0}]
      context: ["registre national", "nrn", "niss"]

    - name: BelgianEnterpriseRecognizer
      supported_language: fr
      supported_entity: BE_ENTERPRISE_NUMBER
      patterns: [{name: BE Enterprise Number, regex: "\\bBE\\s?0\\d{3}[\\.\\s]?\\d{3}[\\.\\s]?\\d{3}\\b", score: 0.95}]
      context: ["numéro d'entreprise", "btw", "tva", "BCE", "KBO"]

# 3. LISTE D'EXCLUSION (ALLOW LIST)
# =====================================================================
allow_list:
  # On garde une liste minimale car les détecteurs sont maintenant plus précis
  - Contrat
  - Document
  - Société
  - Investisseur
  - Montant
  - Prêt
  - Intérêt
  - Partie
  - Parties
  - Annexe
  - Remboursement
  - Conversion
  - Financement
  - Sortie
  - "Juste Valeur Marchande"
  - Échéance
  - Clause
  - Clauses
  - Principe
  - Coûts
  - Notifications
  - Article
  - Paragraphe
  - Directeur
  - Gérant
  - Président
  - DocuSign
  - SPRL
  - SA
  - Loi
  - Code
  - Règlement
  - Décret
  - Arrêté
  - Euro
  - EUR
  - Euros
  - Taux
  - Valeur
  - Prix

# 4. CONFIGURATION DES TRANSFORMATIONS D'ANONYMISATION
# =====================================================================
anonymizer_config:
  default_anonymizers:
    PERSON: replace
    LOCATION: replace
    ORGANIZATION: replace
    DATE_TIME: replace
    CUSTOM_DATE: replace
    CREDIT_CARD_NUMBER: replace
    EMAIL_ADDRESS: replace
    PHONE_NUMBER: replace
    IBAN: replace
    BE_NATIONAL_REGISTER_NUMBER: replace
    BE_ENTERPRISE_NUMBER: replace
    FR_SOCIAL_SECURITY_NUMBER: replace
  
  replacements:
    PERSON: "<PERSONNE>"
    LOCATION: "<LIEU>"
    ORGANIZATION: "<ORGANISATION>"
    DATE_TIME: "<DATE>"
    CUSTOM_DATE: "<DATE>"
    CREDIT_CARD_NUMBER: "<NUMERO_CARTE_BANCAIRE>"
    EMAIL_ADDRESS: "<EMAIL>"
    PHONE_NUMBER: "<TELEPHONE>"
    IBAN: "<IBAN>"
    BE_NATIONAL_REGISTER_NUMBER: "<NRN_BELGE>"
    BE_ENTERPRISE_NUMBER: "<NUM_ENTREPRISE_BE>"
    FR_SOCIAL_SECURITY_NUMBER: "<NUM_SECU_FR>"
