# =====================================================================
# FICHIER DE CONFIGURATION MAÎTRE FINAL ET GARANTI
# =====================================================================

# 1. Configuration du moteur de langage (NLP)
nlp_engine_name: spacy
supported_languages: [en, fr]
models:
  - lang_code: en
    model_name: en_core_web_lg
  - lang_code: fr
    model_name: fr_core_news_sm

# 2. Configuration du comportement du moteur NLP
# On ignore l'étiquette "MISC" pour éviter les faux positifs.
ner_model_configuration:
  labels_to_ignore:
    - MISC

# 3. Configuration des détecteurs (Recognizers)
# LA PARTIE LA PLUS IMPORTANTE - CORRIGÉE
# C'est une liste. On dit à Presidio de charger :
#   - D'ABORD, la collection de tous ses détecteurs par défaut.
#   - ENSUITE, d'ajouter les nôtres depuis notre fichier Python.
recognizer_registry:
  - default
  - presidio_config.custom_recognizers.custom_recognizers

# 4. Configuration de la post-analyse (Allow List)
# Notre filet de sécurité pour les mots à ne jamais anonymiser.
analysis_explanations:
  allow_list:
    - Contrat
    - contrat
    - Contrats
    - Document
    - document
    - Société
    - Investisseur
    - Montant
    - Intérêt
    - Intérêts
    - Partie
    - Parties
    - Annexe
    - Remboursement
    - Conversion
    - Financement
    - Sortie
    - Juste Valeur Marchande
    - Échéance
    - Clause
    - Clauses
    - Principe
    - Coûts
    - Notifications
    - Article
    - Paragraphe
    - Directeur
    - Gérant
    - Président
