# =====================================================================
# CONFIGURATION PRESIDIO - v11 (MAXIMALE FR/BE)
# =====================================================================
supported_languages: [en, fr]

# 1. CONFIGURATION DU MOTEUR NLP
# =====================================================================
nlp_configuration:
  nlp_engine_name: spacy
  models:
    - lang_code: en
      model_name: en_core_web_lg
    - lang_code: fr
      # Utilisation du modèle le plus large et le plus précis
      model_name: fr_core_news_lg 
      ner_model_configuration:
        labels_to_ignore:
          - MISC
          - CARDINAL
          - EVENT
          - LANGUAGE
          - LAW
          - ORDINAL
          - PERCENT
          - PRODUCT
          - QUANTITY
          - WORK_OF_ART
        # Seuils de confiance affinés pour une meilleure détection
        confidence_thresholds:
          DEFAULT_CONFIDENCE: 0.65
          PERSON: 0.65
          LOCATION: 0.35
          ORGANIZATION: 0.4

# 2. CONFIGURATION DU REGISTRE DES DÉTECTEURS
# =====================================================================
recognizer_registry:
  load_predefined_recognizers: true
  
  recognizers:
    # --- DÉTECTEURS FONDAMENTAUX ---
    - name: CustomDateRecognizer
      supported_language: fr
      supported_entity: CUSTOM_DATE
      patterns:
        - name: Date DD/MM/YYYY
          regex: "\\b(0[1-9]|[12][0-9]|3[01])[-/.](0[1-9]|1[012])[-/.](19|20)\\d{2}\\b"
          score: 1.0
      context: ["date de naissance"]
    - name: EmailRecognizer
      supported_language: fr
      supported_entity: EMAIL_ADDRESS
      patterns: [{name: Email Pattern, regex: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b", score: 1.0}]
      context: ["email", "courriel", "mail"]
    - name: PhoneRecognizer
      supported_language: fr
      supported_entity: PHONE_NUMBER
      patterns: [{name: Phone Pattern (FR/BE/LUX), regex: "\\b(?:(?:\\+|00)?(?:32|33|352)|0)\\s?[1-9](?:[\\s.-]?\\d{2}){3,4}\\b", score: 0.8}]
      context: ["téléphone", "tel", "mobile", "gsm", "contact"]
    - name: JobTitleRecognizer
      supported_language: fr
      supported_entity: JOB_TITLE
      patterns:
        - name: Common Job Titles
          regex: "(?i)\\b(Gérant|Directeur des Investissements|Directeur|Directrice|Président|CEO|CFO|CTO|Manager|Responsable|Chef de projet)\\b"
          score: 0.8
      context: ["représentée par", "fonction", "poste", "attention de"]
    - name: PostalCodeRecognizer
      supported_language: fr
      supported_entity: POSTAL_CODE
      patterns:
        - name: Postal Code FR/BE
          regex: "\\b[0-9]{4,5}\\b"
          score: 0.9
      context: ["adresse", "code postal"]

    # --- DÉTECTEURS FINANCIERS ET LÉGAUX ---
    - name: CreditCardRecognizer
      supported_language: fr
      supported_entity: CREDIT_CARD_NUMBER
      patterns:
        - name: Credit Card with spaces
          regex: "\\b(?:4[0-9]{3}(?:[ -]?[0-9]{4}){3}|5[1-5][0-9]{2}(?:[ -]?[0-9]{4}){3})\\b"
          score: 0.95
      context: ["carte bancaire", "visa", "mastercard"]
    - name: IbanRecognizer
      supported_language: fr
      supported_entity: IBAN
      patterns: [{name: IBAN Pattern, regex: "\\b[A-Z]{2}[0-9]{2}\\s?(?:[A-Z0-9]{4}\\s?){2,7}[A-Z0-9]{1,4}\\b", score: 0.95}]
      context: ["iban", "compte", "bancaire"]
    - name: MoneyRecognizer
      supported_language: fr
      supported_entity: MONEY
      patterns:
        - name: Money Pattern EUR
          regex: "(?:EUR|€)\\s*\\d{1,3}(?:[.,\\s]\\d{3})*(?:[.,]\\d{2})?|\\d{1,3}(?:[.,\\s]\\d{3})*(?:[.,]\\d{2})?\\s*(?:EUR|€)"
          score: 0.9
      context: ["montant", "prix", "eur", "euros"]
    - name: CompanyFormRecognizer
      supported_language: fr
      supported_entity: LEGAL_FORM
      patterns:
        - name: Common Legal Forms
          regex: "\\b(SPRL|SARL|SA|SCS|SNC|SCRI|SCA|SRL|SC)\\b"
          score: 0.9
      context: ["société", "entreprise"]

    # --- NUMÉROS D'IDENTIFICATION (FRANCE) ---
    - name: FrenchINSEERecognizer
      supported_language: fr
      supported_entity: FR_SOCIAL_SECURITY_NUMBER
      patterns:
        - name: INSEE Pattern with flexible spaces
          regex: "\\b[12]\\s*[0-9]{2}\\s*(?:0[1-9]|1[0-2])\\s*(?:2[ABab]|[0-9]{2})\\s*[0-9]{3}\\s*[0-9]{3}\\s*[0-9]{2}\\b"
          score: 0.95
      context: ["sécurité sociale", "insee", "nir"]
    - name: FrenchSIRENSIRETRecognizer
      supported_language: fr
      supported_entity: FR_SIREN_SIRET
      patterns:
        - {name: SIRET Pattern, regex: "\\b[0-9]{3}[\\s]?[0-9]{3}[\\s]?[0-9]{3}[\\s]?[0-9]{5}\\b", score: 0.9}
        - {name: SIREN Pattern, regex: "\\b[0-9]{3}[\\s]?[0-9]{3}[\\s]?[0-9]{3}\\b", score: 0.85}
      context: ["siren", "siret"]
    - name: FrenchPassportRecognizer
      supported_language: fr
      supported_entity: FR_PASSPORT
      patterns: [{name: French Passport, regex: "\\b[0-9]{2}[A-Z]{2}[0-9]{5}\\b", score: 1.0}]
      context: ["passeport"]
    - name: FrenchIDCardRecognizer
      supported_language: fr
      supported_entity: FR_ID_CARD_NUMBER
      patterns: [{name: French CNI, regex: "\\b[0-9]{12}\\b", score: 0.8}]
      context: ["cni", "carte nationale d'identité"]
    - name: FrenchLicensePlateRecognizer
      supported_language: fr
      supported_entity: FR_LICENSE_PLATE
      patterns: [{name: French License Plate, regex: "\\b([A-Z]{2}-\\d{3}-[A-Z]{2}|\\d{1,4}\\s[A-Z]{2,3}\\s\\d{2,3})\\b", score: 0.8}]
      context: ["plaque", "immatriculation"]

    # --- NUMÉROS D'IDENTIFICATION (BELGIQUE) ---
    - name: BelgianNRNRecognizer
      supported_language: fr
      supported_entity: BE_NATIONAL_REGISTER_NUMBER
      patterns: [{name: NRN Pattern, regex: "\\b[0-9]{2}\\.[0-9]{2}\\.[0-9]{2}-[0-9]{3}\\.[0-9]{2}\\b", score: 1.0}]
      context: ["registre national", "nrn", "niss"]
    - name: BelgianEnterpriseRecognizer
      supported_language: fr
      supported_entity: BE_ENTERPRISE_NUMBER
      patterns: [{name: BE Enterprise Number, regex: "\\bBE\\s?0\\d{3}[\\.\\s]?\\d{3}[\\.\\s]?\\d{3}\\b", score: 0.95}]
      context: ["numéro d'entreprise", "btw", "tva", "BCE", "KBO"]
    - name: BelgianIDCardRecognizer
      supported_language: fr
      supported_entity: BE_ID_CARD_NUMBER
      patterns: [{name: "Belgian ID Card Number", regex: "\\b\\d{3}-\\d{7}-\\d{2}\\b", score: 1.0}]
      context: ["carte d'identité", "eid"]
    - name: BelgianLicensePlateRecognizer
      supported_language: fr
      supported_entity: BE_LICENSE_PLATE
      patterns: [{name: "Belgian License Plate", regex: "\\b(?:[1-9]-\\w{3}-\\d{3}|\\w{3}-\\d{3})\\b", score: 0.8}]
      context: ["plaque", "immatriculation"]
    - name: BelgianPassportRecognizer
      supported_language: fr
      supported_entity: BE_PASSPORT
      patterns: [{name: Belgian Passport, regex: "\\b[A-Z]{2}\\d{6}\\b", score: 1.0}]
      context: ["passeport"]

# 3. LISTE D'EXCLUSION (ALLOW LIST)
# =====================================================================
allow_list:
  - Contrat
  - Document
  - Société
  - Investisseur
  - Montant
  - Prêt
  - Intérêt
  - Partie
  - Parties
  - Annexe
  - Remboursement
  - Conversion
  - Financement
  - Sortie
  - "Juste Valeur Marchande"
  - Échéance
  - Clause
  - Clauses
  - Principe
  - Coûts
  - Notifications
  - Article
  - Paragraphe
  - Directeur
  - Gérant
  - Président
  - DocuSign
  - SPRL
  - SA
  - Loi
  - Code
  - Règlement
  - Décret
  - Arrêté
  - Euro
  - EUR
  - Euros
  - Taux
  - Valeur
  - Prix

# 4. CONFIGURATION DES TRANSFORMATIONS D'ANONYMISATION
# =====================================================================
anonymizer_config:
  default_anonymizers:
    PERSON: replace
    LOCATION: replace
    ORGANIZATION: replace
    DATE_TIME: replace
    CUSTOM_DATE: replace
    CREDIT_CARD_NUMBER: replace
    EMAIL_ADDRESS: replace
    PHONE_NUMBER: replace
    IBAN: replace
    MONEY: replace
    JOB_TITLE: replace
    POSTAL_CODE: replace
    LEGAL_FORM: replace
    BE_NATIONAL_REGISTER_NUMBER: replace
    BE_ENTERPRISE_NUMBER: replace
    BE_ID_CARD_NUMBER: replace
    BE_LICENSE_PLATE: replace
    BE_PASSPORT: replace
    FR_SOCIAL_SECURITY_NUMBER: replace
    FR_SIREN_SIRET: replace
    FR_PASSPORT: replace
    FR_ID_CARD_NUMBER: replace
    FR_LICENSE_PLATE: replace
  
  replacements:
    PERSON: "<PERSONNE>"
    LOCATION: "<LIEU>"
    ORGANIZATION: "<ORGANISATION>"
    DATE_TIME: "<DATE>"
    CUSTOM_DATE: "<DATE>"
    CREDIT_CARD_NUMBER: "<NUMERO_CARTE_BANCAIRE>"
    EMAIL_ADDRESS: "<EMAIL>"
    PHONE_NUMBER: "<TELEPHONE>"
    IBAN: "<IBAN>"
    MONEY: "<MONTANT>"
    JOB_TITLE: "<FONCTION>"
    POSTAL_CODE: "<CODE_POSTAL>"
    LEGAL_FORM: "<FORME_JURIDIQUE>"
    BE_NATIONAL_REGISTER_NUMBER: "<NRN_BELGE>"
    BE_ENTERPRISE_NUMBER: "<NUM_ENTREPRISE_BE>"
    BE_ID_CARD_NUMBER: "<CARTE_ID_BE>"
    BE_LICENSE_PLATE: "<PLAQUE_BE>"
    BE_PASSPORT: "<PASSEPORT_BE>"
    FR_SOCIAL_SECURITY_NUMBER: "<NUM_SECU_FR>"
    FR_SIREN_SIRET: "<SIREN_SIRET_FR>"
    FR_PASSPORT: "<PASSEPORT_FR>"
    FR_ID_CARD_NUMBER: "<CARTE_ID_FR>"
    FR_LICENSE_PLATE: "<PLAQUE_FR>"
